// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_infoContainer;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_sensorStatus;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label3;
lv_obj_t * ui_wifiStatus;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label9;
lv_obj_t * ui_wifiSSIDLabel;
lv_obj_t * ui_bpmChart;
lv_obj_t * ui_bpmChart_Xaxis;
lv_obj_t * ui_bpmChart_Yaxis1;
lv_obj_t * ui_bpmChart_Yaxis2;
lv_obj_t * ui_bpmChart1;
lv_obj_t * ui_bpmChart1_Xaxis;
lv_obj_t * ui_bpmChart1_Yaxis1;
lv_obj_t * ui_bpmChart1_Yaxis2;
lv_obj_t * ui_bpmChart2;
lv_obj_t * ui_bpmChart2_Xaxis;
lv_obj_t * ui_bpmChart2_Yaxis1;
lv_obj_t * ui_bpmChart2_Yaxis2;
lv_obj_t * ui_hrContainer;
lv_obj_t * ui_hrImgLabel;
lv_obj_t * ui_hrInfoContainer;
lv_obj_t * ui_hrLabelContainer;
lv_obj_t * ui_heartRate;
lv_obj_t * ui_hrDetailInfoContainer;
lv_obj_t * ui_bpmLabel;
lv_obj_t * ui_hrSubText;
lv_obj_t * ui_hrContainer1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_hrInfoContainer1;
lv_obj_t * ui_hrLabelContainer1;
lv_obj_t * ui_SpO2;
lv_obj_t * ui_hrDetailInfoContainer1;
lv_obj_t * ui_spo2Label;
lv_obj_t * ui_hrSubText5;
lv_obj_t * ui_hrContainer2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_hrInfoContainer2;
lv_obj_t * ui_hrLabelContainer2;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_hrDetailInfoContainer2;
lv_obj_t * ui_tempLabel;
lv_obj_t * ui_hrSubText7;
// CUSTOM VARIABLES
lv_obj_t * wm_MainScreen;
lv_obj_t * wm_infoContainer;
lv_obj_t * wm_channLabel;
lv_obj_t * wm_sensorStatus;
lv_obj_t * wm_sensorAddrLabel;
lv_obj_t * wm_wifiStatus;
lv_obj_t * wm_wifiSSIDLabel;
lv_obj_t * wm_bpmChart;
lv_obj_t * wm_spO2Chart;
lv_obj_t * wm_tempChart;
lv_obj_t * wm_hrContainer;
lv_obj_t * wm_hrImgLabel;
lv_obj_t * wm_hrInfoContainer;
lv_obj_t * wm_hrLabelContainer;
lv_obj_t * wm_hrDetailInfoContainer;
lv_obj_t * wm_bpmLabel;
lv_obj_t * wm_spo2Label;
lv_obj_t * wm_tempLabel;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
