// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_infoContainer;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_sensorStatus;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_wifiStatus;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_wifiSSIDLabel;
extern lv_obj_t * ui_bpmChart;
extern lv_obj_t * ui_bpmChart_Xaxis;
extern lv_obj_t * ui_bpmChart_Yaxis1;
extern lv_obj_t * ui_bpmChart_Yaxis2;
extern lv_obj_t * ui_bpmChart1;
extern lv_obj_t * ui_bpmChart1_Xaxis;
extern lv_obj_t * ui_bpmChart1_Yaxis1;
extern lv_obj_t * ui_bpmChart1_Yaxis2;
extern lv_obj_t * ui_bpmChart2;
extern lv_obj_t * ui_bpmChart2_Xaxis;
extern lv_obj_t * ui_bpmChart2_Yaxis1;
extern lv_obj_t * ui_bpmChart2_Yaxis2;
extern lv_obj_t * ui_hrContainer;
extern lv_obj_t * ui_hrImgLabel;
extern lv_obj_t * ui_hrInfoContainer;
extern lv_obj_t * ui_hrLabelContainer;
extern lv_obj_t * ui_heartRate;
extern lv_obj_t * ui_hrDetailInfoContainer;
extern lv_obj_t * ui_bpmLabel;
extern lv_obj_t * ui_hrSubText;
extern lv_obj_t * ui_hrContainer1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_hrInfoContainer1;
extern lv_obj_t * ui_hrLabelContainer1;
extern lv_obj_t * ui_SpO2;
extern lv_obj_t * ui_hrDetailInfoContainer1;
extern lv_obj_t * ui_spo2Label;
extern lv_obj_t * ui_hrSubText5;
extern lv_obj_t * ui_hrContainer2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_hrInfoContainer2;
extern lv_obj_t * ui_hrLabelContainer2;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_hrDetailInfoContainer2;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_hrSubText7;
// CUSTOM VARIABLES
extern lv_obj_t * wm_MainScreen;
extern lv_obj_t * wm_infoContainer;
extern lv_obj_t * wm_channLabel;
extern lv_obj_t * wm_sensorStatus;
extern lv_obj_t * wm_sensorAddrLabel;
extern lv_obj_t * wm_wifiStatus;
extern lv_obj_t * wm_wifiSSIDLabel;
extern lv_obj_t * wm_bpmChart;
extern lv_obj_t * wm_spO2Chart;
extern lv_obj_t * wm_tempChart;
extern lv_obj_t * wm_hrContainer;
extern lv_obj_t * wm_hrImgLabel;
extern lv_obj_t * wm_hrInfoContainer;
extern lv_obj_t * wm_hrLabelContainer;
extern lv_obj_t * wm_hrDetailInfoContainer;
extern lv_obj_t * wm_bpmLabel;
extern lv_obj_t * wm_spo2Label;
extern lv_obj_t * wm_tempLabel;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_cardiology_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);    // assets/cardiology_16dp_E2D5CF_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_spo2_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);    // assets/spo2_16dp_E2D5CF_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_thermometer_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);    // assets/thermometer_16dp_E2D5CF_FILL0_wght400_GRAD0_opsz20.png

// FONTS
LV_FONT_DECLARE(ui_font_Lexend_10);
LV_FONT_DECLARE(ui_font_Lexend_12);
LV_FONT_DECLARE(ui_font_Lexend_20);
LV_FONT_DECLARE(ui_font_Lexend_24);
LV_FONT_DECLARE(ui_font_Lexend_32);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
