// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infoContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_infoContainer);
    lv_obj_set_width(ui_infoContainer, 480);
    lv_obj_set_height(ui_infoContainer, 63);
    lv_obj_set_x(ui_infoContainer, 1);
    lv_obj_set_y(ui_infoContainer, -128);
    lv_obj_set_align(ui_infoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_infoContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_infoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_infoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_infoContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_infoContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_border_width(ui_infoContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_infoContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container6, 1);
    lv_obj_set_x(ui_Container6, -157);
    lv_obj_set_y(ui_Container6, -130);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container6, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Channel");
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "10");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Lexend_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container1, 1);
    lv_obj_set_x(ui_Container1, -157);
    lv_obj_set_y(ui_Container1, -130);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container7, 1);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Sensors");
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorStatus = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sensorStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sensorStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorStatus, "OK");
    ui_object_set_themeable_style_property(ui_sensorStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Success);
    ui_object_set_themeable_style_property(ui_sensorStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Success);
    lv_obj_set_style_text_font(ui_sensorStatus, &ui_font_Lexend_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_height(ui_Container8, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container8, 1);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MAC");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label2, lv_pct(82));
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "00:00:0A:BB:28:FC");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_infoContainer);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container2, 1);
    lv_obj_set_x(ui_Container2, -157);
    lv_obj_set_y(ui_Container2, -130);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container9, 1);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Network");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatus = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStatus, "ERR");
    ui_object_set_themeable_style_property(ui_wifiStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Error);
    ui_object_set_themeable_style_property(ui_wifiStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Error);
    lv_obj_set_style_text_font(ui_wifiStatus, &ui_font_Lexend_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_height(ui_Container10, lv_pct(100));
    lv_obj_set_flex_grow(ui_Container10, 1);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SSID:");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSSIDLabel = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_wifiSSIDLabel, lv_pct(82));
    lv_obj_set_height(ui_wifiSSIDLabel, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_wifiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiSSIDLabel, "Tam Anh Hospital");
    ui_object_set_themeable_style_property(ui_wifiSSIDLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_wifiSSIDLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_align(ui_wifiSSIDLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiSSIDLabel, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bpmChart = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_bpmChart, 200);
    lv_obj_set_height(ui_bpmChart, 50);
    lv_obj_set_x(ui_bpmChart, 111);
    lv_obj_set_y(ui_bpmChart, -59);
    lv_obj_set_align(ui_bpmChart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bpmChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_bpmChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_bpmChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_bpmChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_bpmChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_bpmChart, 5);
    lv_chart_set_range(ui_bpmChart, LV_CHART_AXIS_PRIMARY_Y, 30, 130);
    lv_chart_set_div_line_count(ui_bpmChart, 3, 2);

    ui_bpmChart_Xaxis = lv_scale_create(ui_bpmChart);
    lv_scale_set_mode(ui_bpmChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_bpmChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_bpmChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_bpmChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_bpmChart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_bpmChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_bpmChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_bpmChart_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_bpmChart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_bpmChart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart_Xaxis, 1 >= 1 ? 1 : 1);
    ui_bpmChart_Yaxis1 = lv_scale_create(ui_bpmChart);
    lv_scale_set_mode(ui_bpmChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_bpmChart_Yaxis1, 10, lv_pct(100));
    lv_obj_set_align(ui_bpmChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_bpmChart_Yaxis1, -10 - lv_obj_get_style_pad_left(ui_bpmChart,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_bpmChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_bpmChart_Yaxis1,  30, 130);
    lv_scale_set_total_tick_count(ui_bpmChart_Yaxis1, (3 > 0 ? 3 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart_Yaxis1, 1 >= 1 ? 1 : 1);
    ui_bpmChart_Yaxis2 = lv_scale_create(ui_bpmChart);
    lv_scale_set_mode(ui_bpmChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_bpmChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_bpmChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_bpmChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_bpmChart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_bpmChart_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_bpmChart_Yaxis2, false);
    lv_chart_series_t * ui_bpmChart_series_1 = lv_chart_add_series(ui_bpmChart, lv_color_hex(0xE2D5CF),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_bpmChart_series_1_array[] = { 12 };
    lv_chart_set_ext_y_array(ui_bpmChart, ui_bpmChart_series_1, ui_bpmChart_series_1_array);

    ui_object_set_themeable_style_property(ui_bpmChart_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_bpmChart_Xaxis, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart_Yaxis1, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart_Yaxis2, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_bpmChart, LV_MAX3(50, 10, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_bpmChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_bpmChart1 = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_bpmChart1, 200);
    lv_obj_set_height(ui_bpmChart1, 50);
    lv_obj_set_x(ui_bpmChart1, 111);
    lv_obj_set_y(ui_bpmChart1, 25);
    lv_obj_set_align(ui_bpmChart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bpmChart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_bpmChart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_bpmChart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_bpmChart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_bpmChart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_bpmChart1, 5);
    lv_chart_set_range(ui_bpmChart1, LV_CHART_AXIS_PRIMARY_Y, 80, 100);
    lv_chart_set_div_line_count(ui_bpmChart1, 3, 2);

    ui_bpmChart1_Xaxis = lv_scale_create(ui_bpmChart1);
    lv_scale_set_mode(ui_bpmChart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_bpmChart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_bpmChart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_bpmChart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_bpmChart1,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_bpmChart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_bpmChart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_bpmChart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_bpmChart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_bpmChart1_Xaxis, (5 > 0 ? 5 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart1_Xaxis, 1 >= 1 ? 1 : 1);
    ui_bpmChart1_Yaxis1 = lv_scale_create(ui_bpmChart1);
    lv_scale_set_mode(ui_bpmChart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_bpmChart1_Yaxis1, 10, lv_pct(100));
    lv_obj_set_align(ui_bpmChart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_bpmChart1_Yaxis1, -10 - lv_obj_get_style_pad_left(ui_bpmChart1,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_bpmChart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_bpmChart1_Yaxis1,  80, 100);
    lv_scale_set_total_tick_count(ui_bpmChart1_Yaxis1, (3 > 0 ? 3 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart1_Yaxis1, 1 >= 1 ? 1 : 1);
    ui_bpmChart1_Yaxis2 = lv_scale_create(ui_bpmChart1);
    lv_scale_set_mode(ui_bpmChart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_bpmChart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_bpmChart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_bpmChart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_bpmChart1,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart1_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_bpmChart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart1_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_bpmChart1_series_1 = lv_chart_add_series(ui_bpmChart1, lv_color_hex(0xE2D5CF),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_bpmChart1_series_1_array[] = { 80, 82, 89, 100, 100, 100, 100, 100, 100, 100, 100 };
    lv_chart_set_ext_y_array(ui_bpmChart1, ui_bpmChart1_series_1, ui_bpmChart1_series_1_array);

    ui_object_set_themeable_style_property(ui_bpmChart1_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart1_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart1_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart1_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart1_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart1_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_bpmChart1_Xaxis, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart1_Yaxis1, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart1_Yaxis2, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_bpmChart1, LV_MAX3(50, 10, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_bpmChart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_bpmChart2 = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_bpmChart2, 200);
    lv_obj_set_height(ui_bpmChart2, 50);
    lv_obj_set_x(ui_bpmChart2, 111);
    lv_obj_set_y(ui_bpmChart2, 107);
    lv_obj_set_align(ui_bpmChart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bpmChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_bpmChart2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_bpmChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_bpmChart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_bpmChart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_bpmChart2, 5);
    lv_chart_set_range(ui_bpmChart2, LV_CHART_AXIS_PRIMARY_Y, 30, 130);
    lv_chart_set_div_line_count(ui_bpmChart2, 3, 2);

    ui_bpmChart2_Xaxis = lv_scale_create(ui_bpmChart2);
    lv_scale_set_mode(ui_bpmChart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_bpmChart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_bpmChart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_bpmChart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_bpmChart2,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_bpmChart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_bpmChart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_bpmChart2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_bpmChart2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_bpmChart2_Xaxis, (5 > 0 ? 5 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart2_Xaxis, 1 >= 1 ? 1 : 1);
    ui_bpmChart2_Yaxis1 = lv_scale_create(ui_bpmChart2);
    lv_scale_set_mode(ui_bpmChart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_bpmChart2_Yaxis1, 10, lv_pct(100));
    lv_obj_set_align(ui_bpmChart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_bpmChart2_Yaxis1, -10 - lv_obj_get_style_pad_left(ui_bpmChart2,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_bpmChart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart2_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_bpmChart2_Yaxis1,  30, 130);
    lv_scale_set_total_tick_count(ui_bpmChart2_Yaxis1, (3 > 0 ? 3 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart2_Yaxis1, 1 >= 1 ? 1 : 1);
    ui_bpmChart2_Yaxis2 = lv_scale_create(ui_bpmChart2);
    lv_scale_set_mode(ui_bpmChart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_bpmChart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_bpmChart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_bpmChart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_bpmChart2,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_bpmChart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_bpmChart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_bpmChart2_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_bpmChart2_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_bpmChart2_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_bpmChart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_bpmChart2_series_1 = lv_chart_add_series(ui_bpmChart2, lv_color_hex(0xE2D5CF),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_bpmChart2_series_1_array[] = { 80, 82, 89, 100, 100, 100, 100, 100, 100, 100, 100 };
    lv_chart_set_ext_y_array(ui_bpmChart2, ui_bpmChart2_series_1, ui_bpmChart2_series_1_array);

    ui_object_set_themeable_style_property(ui_bpmChart2_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart2_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart2_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart2_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart2_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmChart2_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_bpmChart2_Xaxis, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart2_Yaxis1, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpmChart2_Yaxis2, &ui_font_Lexend_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_bpmChart2, LV_MAX3(50, 10, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_bpmChart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_hrContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_hrContainer);
    lv_obj_set_width(ui_hrContainer, 180);
    lv_obj_set_height(ui_hrContainer, 57);
    lv_obj_set_x(ui_hrContainer, 20);
    lv_obj_set_y(ui_hrContainer, -46);
    lv_obj_set_align(ui_hrContainer, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hrImgLabel = lv_image_create(ui_hrContainer);
    lv_image_set_src(ui_hrImgLabel, &ui_img_cardiology_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_hrImgLabel, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_hrImgLabel, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_hrImgLabel, -193);
    lv_obj_set_y(ui_hrImgLabel, -51);
    lv_obj_set_align(ui_hrImgLabel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hrImgLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_hrImgLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_hrImgLabel, 200);

    ui_hrInfoContainer = lv_obj_create(ui_hrContainer);
    lv_obj_remove_style_all(ui_hrInfoContainer);
    lv_obj_set_width(ui_hrInfoContainer, 122);
    lv_obj_set_height(ui_hrInfoContainer, lv_pct(100));
    lv_obj_set_x(ui_hrInfoContainer, 83);
    lv_obj_set_y(ui_hrInfoContainer, -43);
    lv_obj_set_align(ui_hrInfoContainer, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrInfoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_hrInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hrLabelContainer = lv_obj_create(ui_hrInfoContainer);
    lv_obj_remove_style_all(ui_hrLabelContainer);
    lv_obj_set_width(ui_hrLabelContainer, 100);
    lv_obj_set_height(ui_hrLabelContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_hrLabelContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrLabelContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrLabelContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrLabelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heartRate = lv_label_create(ui_hrLabelContainer);
    lv_obj_set_width(ui_heartRate, lv_pct(100));
    lv_obj_set_height(ui_heartRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heartRate, 80);
    lv_obj_set_y(ui_heartRate, -65);
    lv_obj_set_align(ui_heartRate, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_heartRate, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_heartRate, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_heartRate, "Heart Rate");
    ui_object_set_themeable_style_property(ui_heartRate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_heartRate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_heartRate, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrDetailInfoContainer = lv_obj_create(ui_hrInfoContainer);
    lv_obj_remove_style_all(ui_hrDetailInfoContainer);
    lv_obj_set_width(ui_hrDetailInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_hrDetailInfoContainer, lv_pct(50));
    lv_obj_set_align(ui_hrDetailInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrDetailInfoContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrDetailInfoContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrDetailInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bpmLabel = lv_label_create(ui_hrDetailInfoContainer);
    lv_obj_set_width(ui_bpmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bpmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bpmLabel, 80);
    lv_obj_set_y(ui_bpmLabel, -40);
    lv_obj_set_align(ui_bpmLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_bpmLabel, "70.55");
    ui_object_set_themeable_style_property(ui_bpmLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_bpmLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_bpmLabel, &ui_font_Lexend_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrSubText = lv_label_create(ui_hrDetailInfoContainer);
    lv_obj_set_width(ui_hrSubText, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_hrSubText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hrSubText, -61);
    lv_obj_set_y(ui_hrSubText, -35);
    lv_obj_set_align(ui_hrSubText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hrSubText, "BPM");
    ui_object_set_themeable_style_property(ui_hrSubText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_hrSubText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_hrSubText, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrContainer1 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_hrContainer1);
    lv_obj_set_width(ui_hrContainer1, 180);
    lv_obj_set_height(ui_hrContainer1, 57);
    lv_obj_set_x(ui_hrContainer1, 20);
    lv_obj_set_y(ui_hrContainer1, 20);
    lv_obj_set_align(ui_hrContainer1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_hrContainer1);
    lv_image_set_src(ui_Image3, &ui_img_spo2_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, -193);
    lv_obj_set_y(ui_Image3, 24);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 200);

    ui_hrInfoContainer1 = lv_obj_create(ui_hrContainer1);
    lv_obj_remove_style_all(ui_hrInfoContainer1);
    lv_obj_set_width(ui_hrInfoContainer1, 122);
    lv_obj_set_height(ui_hrInfoContainer1, lv_pct(100));
    lv_obj_set_x(ui_hrInfoContainer1, 83);
    lv_obj_set_y(ui_hrInfoContainer1, -43);
    lv_obj_set_align(ui_hrInfoContainer1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrInfoContainer1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_hrInfoContainer1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrInfoContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hrLabelContainer1 = lv_obj_create(ui_hrInfoContainer1);
    lv_obj_remove_style_all(ui_hrLabelContainer1);
    lv_obj_set_width(ui_hrLabelContainer1, 100);
    lv_obj_set_height(ui_hrLabelContainer1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_hrLabelContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrLabelContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrLabelContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrLabelContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpO2 = lv_label_create(ui_hrLabelContainer1);
    lv_obj_set_width(ui_SpO2, lv_pct(100));
    lv_obj_set_height(ui_SpO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2, 80);
    lv_obj_set_y(ui_SpO2, -65);
    lv_obj_set_align(ui_SpO2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_SpO2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SpO2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_SpO2, "SpO2");
    ui_object_set_themeable_style_property(ui_SpO2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_SpO2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_SpO2, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrDetailInfoContainer1 = lv_obj_create(ui_hrInfoContainer1);
    lv_obj_remove_style_all(ui_hrDetailInfoContainer1);
    lv_obj_set_width(ui_hrDetailInfoContainer1, lv_pct(100));
    lv_obj_set_height(ui_hrDetailInfoContainer1, lv_pct(50));
    lv_obj_set_align(ui_hrDetailInfoContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrDetailInfoContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrDetailInfoContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrDetailInfoContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spo2Label = lv_label_create(ui_hrDetailInfoContainer1);
    lv_obj_set_width(ui_spo2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2Label, 80);
    lv_obj_set_y(ui_spo2Label, -40);
    lv_obj_set_align(ui_spo2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_spo2Label, "100");
    ui_object_set_themeable_style_property(ui_spo2Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_spo2Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_spo2Label, &ui_font_Lexend_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrSubText5 = lv_label_create(ui_hrDetailInfoContainer1);
    lv_obj_set_width(ui_hrSubText5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_hrSubText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hrSubText5, -61);
    lv_obj_set_y(ui_hrSubText5, -35);
    lv_obj_set_align(ui_hrSubText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hrSubText5, "%");
    ui_object_set_themeable_style_property(ui_hrSubText5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_hrSubText5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_hrSubText5, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrContainer2 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_hrContainer2);
    lv_obj_set_width(ui_hrContainer2, 180);
    lv_obj_set_height(ui_hrContainer2, 57);
    lv_obj_set_x(ui_hrContainer2, 20);
    lv_obj_set_y(ui_hrContainer2, 100);
    lv_obj_set_align(ui_hrContainer2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_hrContainer2);
    lv_image_set_src(ui_Image4, &ui_img_thermometer_16dp_e2d5cf_fill0_wght400_grad0_opsz20_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 115
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image4, -195);
    lv_obj_set_y(ui_Image4, 106);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 200);

    ui_hrInfoContainer2 = lv_obj_create(ui_hrContainer2);
    lv_obj_remove_style_all(ui_hrInfoContainer2);
    lv_obj_set_width(ui_hrInfoContainer2, 122);
    lv_obj_set_height(ui_hrInfoContainer2, lv_pct(100));
    lv_obj_set_x(ui_hrInfoContainer2, 83);
    lv_obj_set_y(ui_hrInfoContainer2, -43);
    lv_obj_set_align(ui_hrInfoContainer2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_hrInfoContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_hrInfoContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrInfoContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hrLabelContainer2 = lv_obj_create(ui_hrInfoContainer2);
    lv_obj_remove_style_all(ui_hrLabelContainer2);
    lv_obj_set_width(ui_hrLabelContainer2, 100);
    lv_obj_set_height(ui_hrLabelContainer2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_hrLabelContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrLabelContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrLabelContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrLabelContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature = lv_label_create(ui_hrLabelContainer2);
    lv_obj_set_width(ui_Temperature, lv_pct(100));
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 80);
    lv_obj_set_y(ui_Temperature, -65);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Temperature, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Temperature, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Temperature, "Temperature");
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrDetailInfoContainer2 = lv_obj_create(ui_hrInfoContainer2);
    lv_obj_remove_style_all(ui_hrDetailInfoContainer2);
    lv_obj_set_width(ui_hrDetailInfoContainer2, lv_pct(100));
    lv_obj_set_height(ui_hrDetailInfoContainer2, lv_pct(50));
    lv_obj_set_align(ui_hrDetailInfoContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hrDetailInfoContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hrDetailInfoContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_hrDetailInfoContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLabel = lv_label_create(ui_hrDetailInfoContainer2);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, 80);
    lv_obj_set_y(ui_tempLabel, -40);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_tempLabel, "36.50");
    ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_tempLabel, &ui_font_Lexend_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrSubText7 = lv_label_create(ui_hrDetailInfoContainer2);
    lv_obj_set_width(ui_hrSubText7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_hrSubText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hrSubText7, -61);
    lv_obj_set_y(ui_hrSubText7, -35);
    lv_obj_set_align(ui_hrSubText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hrSubText7, "°C");
    ui_object_set_themeable_style_property(ui_hrSubText7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_On_Surface);
    ui_object_set_themeable_style_property(ui_hrSubText7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_On_Surface);
    lv_obj_set_style_text_font(ui_hrSubText7, &ui_font_Lexend_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    wm_MainScreen = ui_MainScreen;
    wm_infoContainer = ui_infoContainer;
    wm_channLabel = ui_Label7;
    wm_sensorStatus = ui_sensorStatus;
    wm_sensorAddrLabel = ui_Label2;
    wm_wifiStatus = ui_wifiStatus;
    wm_wifiSSIDLabel = ui_wifiSSIDLabel;
    wm_bpmChart = ui_bpmChart;
    wm_spO2Chart = ui_bpmChart1;
    wm_tempChart = ui_bpmChart2;
    wm_hrContainer = ui_hrContainer;
    wm_hrImgLabel = ui_hrImgLabel;
    wm_hrInfoContainer = ui_hrInfoContainer;
    wm_hrLabelContainer = ui_hrLabelContainer;
    wm_hrDetailInfoContainer = ui_hrDetailInfoContainer;
    wm_bpmLabel = ui_bpmLabel;
    wm_spo2Label = ui_spo2Label;
    wm_tempLabel = ui_tempLabel;

}
