// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_SURFACE 0
#define UI_THEME_COLOR_ON_SURFACE 1
#define UI_THEME_COLOR_ERROR 2
#define UI_THEME_COLOR_SUCCESS 3
#define UI_THEME_COLOR_WARN 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_WIMON 1

extern const ui_theme_variable_t _ui_theme_color_Surface[2];
extern const ui_theme_variable_t _ui_theme_alpha_Surface[2];

extern const ui_theme_variable_t _ui_theme_color_On_Surface[2];
extern const ui_theme_variable_t _ui_theme_alpha_On_Surface[2];

extern const ui_theme_variable_t _ui_theme_color_Error[2];
extern const ui_theme_variable_t _ui_theme_alpha_Error[2];

extern const ui_theme_variable_t _ui_theme_color_Success[2];
extern const ui_theme_variable_t _ui_theme_alpha_Success[2];

extern const ui_theme_variable_t _ui_theme_color_Warn[2];
extern const ui_theme_variable_t _ui_theme_alpha_Warn[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
